<a href="https://colab.research.google.com/github/ManasviAtGitHub/PyTorch-practice/blob/main/Tensors_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors 

In [ ]:
import torch

## zeros()

In [ ]:
w = torch.zeros(4,3)

In [ ]:
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [ ]:
w.size()

torch.Size([4, 3])

In [ ]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [ ]:
w = torch.randn(4,3) #normal distributed
w

tensor([[-0.0800,  2.6685, -1.3303],
        [ 0.7506,  0.0447,  2.0990],
        [ 0.4976, -1.0103,  0.5695],
        [-0.7674,  0.8013,  0.8934]])

In [ ]:
t = torch.randn_like(w)
t

tensor([[ 0.5423,  0.7350,  0.4510],
        [-0.9726,  1.1335,  0.5237],
        [ 0.9292,  0.1286,  0.3635],
        [ 0.8625,  1.9106, -1.7088]])

## fill_()

In [ ]:
w.fill_(1) #changes inplace (usually name is followed by _)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [ ]:
t = w.view(3,4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
t = w.view(3,-1)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()

In [ ]:
type(t)

torch.Tensor

In [ ]:
t.numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [ ]:
type(t.numpy())

numpy.ndarray